"""CMake files for a Solution that configure and build without CppBuild.

Each Solution gets a CMakeLists.txt (its member Projects, independent of who
includes it) and CppBuildTopLevel.cmake (build defaults and the linked
Solutions resolved with it as the top level). Each Project gets a
CMakeLists.txt in its directory. Paths are relative, the content does not
depend on the generator, compiler, architecture or other non-saved settings,
and the same input always produces the same bytes.

Non-saved settings reach CMake as cache variables (see workspace.cache_script).
"""
import os
from pathlib import Path
import uuid

from . import storage
from .models import CMakePackage, CMakeSource, Dependency, ImportedLibrary, ProjectType, SettingsError

MARKER = "# Generated by CppBuild"
ENTRY = "CMakeLists.txt"
TOP_LEVEL = "CppBuildTopLevel.cmake"
CONFIGURATIONS = ("Debug", "Release", "RelWithDebInfo", "MinSizeRel")
GOOGLETEST_URL = "https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip"
GOOGLETEST_SHA256 = "1f357c27ca988c3f7c6b4bf68a9395005ac6761f034046e9dde0896e3aba00e4"
COMPILED_SUFFIXES = {".cpp", ".cc", ".cxx"}
# The conventions between generated files (CPPBUILD_REQUEST_*, aliases, ...). A linked
# Solution's files must use the same one, e.g. when they come from another repository.
FORMAT = 1
# Same rules as git_sources.fetch(): clone a missing place at the recorded commit through a
# temporary directory; never change an existing place, only compare it with the record.
GIT_SOURCE_FUNCTION = r'''function(_cppbuild_git_source directory url revision solution)
  set(_place "${CMAKE_CURRENT_SOURCE_DIR}/${directory}")
  find_package(Git QUIET)
  if(EXISTS "${_place}/${solution}/project.json")
    if(GIT_EXECUTABLE AND EXISTS "${_place}/.git")
      execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_place}" rev-parse HEAD
        RESULT_VARIABLE _result OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(_result EQUAL 0 AND NOT _head STREQUAL revision)
        message(WARNING "${directory} is at ${_head}, but ${revision} is recorded for ${url}; it is left unchanged")
      endif()
    endif()
    return()
  endif()
  if(EXISTS "${_place}")
    set(_reason "the place exists without ${solution}/project.json")
  elseif(NOT CPPBUILD_FETCH)
    set(_reason "CPPBUILD_FETCH is OFF")
  elseif(NOT GIT_EXECUTABLE)
    set(_reason "git was not found")
  else()
    set(_temporary "${_place}.cppbuild-fetch")
    file(REMOVE_RECURSE "${_temporary}")
    message(STATUS "CppBuild: cloning ${url} at ${revision} into ${directory}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" clone --no-checkout -- "${url}" "${_temporary}"
      RESULT_VARIABLE _result OUTPUT_QUIET ERROR_VARIABLE _error)
    if(_result EQUAL 0)
      execute_process(COMMAND "${GIT_EXECUTABLE}" -c advice.detachedHead=false -C "${_temporary}" checkout --detach "${revision}"
        RESULT_VARIABLE _result OUTPUT_QUIET ERROR_VARIABLE _error)
    endif()
    if(_result EQUAL 0 AND EXISTS "${_temporary}/${solution}/project.json")
      file(RENAME "${_temporary}" "${_place}")
      return()
    endif()
    file(REMOVE_RECURSE "${_temporary}")
    if(_result EQUAL 0)
      set(_error "no CppBuild Solution at ${solution}")
    endif()
    string(STRIP "${_error}" _error)
    string(REPLACE "\n" " " _reason "git failed: ${_error}")
  endif()
  set_property(GLOBAL APPEND_STRING PROPERTY CPPBUILD_GIT_MISSING
    "\n  ${directory}: ${url} at ${revision} (${_reason})\n    git clone ${url} ${directory} && git -C ${directory} checkout ${revision}")
endfunction()'''
KIND = {ProjectType.STATIC_LIBRARY: "STATIC", ProjectType.SHARED_LIBRARY: "SHARED",
        ProjectType.INTERFACE_LIBRARY: "INTERFACE", ProjectType.EXECUTABLE: "EXECUTABLE", ProjectType.TEST: "TEST"}
SUFFIX = {ProjectType.STATIC_LIBRARY: "static", ProjectType.SHARED_LIBRARY: "shared",
          ProjectType.INTERFACE_LIBRARY: "interface"}
LIBRARY_ORDER = (ProjectType.STATIC_LIBRARY, ProjectType.SHARED_LIBRARY, ProjectType.INTERFACE_LIBRARY)


# Names -----------------------------------------------------------------------

def base_name(project):
    """The CMake target name of a Project's initial type, unique across Solutions."""
    return f"{project.solution.settings._data.name}_{project.name}"


def alias_name(project):
    return f"{project.solution.settings._data.name}::{project.name}"


def target_name(project, kind):
    base = base_name(project)
    return base if kind == project.settings._data.initial_type else f"{base}_{SUFFIX[kind]}"


def link_name(project, kind):
    """The ALIAS a consumer links for a saved link type; the provider maps it to a target."""
    return f"{alias_name(project)}_{SUFFIX[kind]}"


def request_variable(project_guid):
    return "CPPBUILD_REQUEST_" + uuid.UUID(project_guid).hex


def type_variable(project):
    return base_name(project) + "_TYPE"


def standard_variable(project):
    return base_name(project) + "_CXX_STANDARD"


def output_variable(project):
    return base_name(project) + "_OUTPUT_DIRECTORY"


def is_generated(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as stream:
            return stream.readline().startswith(MARKER)
    except OSError:
        return False


def generated_file(path):
    path = Path(path)
    return path.name in {ENTRY, TOP_LEVEL} and path.is_file() and is_generated(path)


# CMake syntax ----------------------------------------------------------------

def arg(value):
    """A quoted CMake argument whose content is never expanded."""
    text = str(value)
    # Generator expressions are evaluated even inside bracket arguments.
    if any(c in text for c in ("\x00", "\n", "\r", ";", "$<")):
        raise SettingsError(f"Unsupported CMake literal: {text!r}")
    if any(c in text for c in '"\\$@'):
        delimiter = "="
        while f"]{delimiter}]" in text:
            delimiter += "="
        return f"[{delimiter}[{text}]{delimiter}]"
    return f'"{text}"'


def _relative(base, target, what):
    try:
        value = Path(os.path.relpath(target, base)).as_posix()
    except ValueError as exc:
        raise SettingsError(f"{what} must be on the same drive as {base} to be written as a relative path") from exc
    return value


def _source_path(base, target, what):
    """A path below ${CMAKE_CURRENT_SOURCE_DIR} for commands that need a full path."""
    value = _relative(base, target, what)
    if any(c in value for c in '"\\$@;'):
        raise SettingsError(f"{what} contains characters CMake cannot quote here: {value}")
    return '"${CMAKE_CURRENT_SOURCE_DIR}/' + value + '"'


def _quotable(value):
    if any(c in value for c in '"\\$;'):
        raise SettingsError(f"Path contains characters CMake cannot quote here: {value}")
    return value


def _header(source, description):
    return [f"{MARKER} from {source}. Do not edit: CppBuild rewrites this file.", f"# {description}", ""]


# Solution entry ----------------------------------------------------------------

def internal_requests(solution):
    """Link types requested between members of one Solution, by provider GUID."""
    local = {p.settings._data.guid for p in solution.projects()}
    result = {}
    for project in solution.projects():
        for dependency in project.settings._data.dependencies.values():
            if isinstance(dependency, Dependency) and dependency.project_guid in local:
                result.setdefault(dependency.project_guid, set()).add(dependency.project_type)
    return result


def _member_folder(solution, project):
    folders = solution.settings._data.solution_folders
    if folders is None:
        return None
    child = folders.project_folders.get(project.name, "")
    return folders.projects + ("/" + child if child else "")


def solution_entry(solution):
    data = solution.settings._data
    requests = internal_requests(solution)
    lines = _header(".cppbuild/project.json", f"Solution {data.name}: configure with cmake -S <this directory> -B <build directory>.")
    lines += ["cmake_minimum_required(VERSION 3.24)", f"project({data.name} LANGUAGES CXX)",
              f"set_property(DIRECTORY PROPERTY CPPBUILD_FORMAT {FORMAT})  # checked by the including Solution", "",
              "# Every member is added, with this Solution's linked Solutions, unless another CppBuild",
              "# Solution includes this one (CPPBUILD_LINKED) and requests only the Projects it needs.",
              "set(CPPBUILD_WHOLE_SOLUTION OFF)",
              "if(PROJECT_IS_TOP_LEVEL OR NOT CPPBUILD_LINKED)",
              "  set(CPPBUILD_WHOLE_SOLUTION ON)",
              f'  if(NOT EXISTS "${{CMAKE_CURRENT_SOURCE_DIR}}/{TOP_LEVEL}")',
              f'    message(FATAL_ERROR "{TOP_LEVEL} is missing; regenerate it with CppBuild (Solution.update)")',
              "  endif()",
              f'  include("${{CMAKE_CURRENT_SOURCE_DIR}}/{TOP_LEVEL}")',
              "endif()"]
    for project in sorted(solution.projects(), key=lambda p: p.name):
        guid = project.settings._data.guid
        variable = request_variable(guid)
        kinds = sorted(KIND[k] for k in requests.get(guid, ()))
        folder = _member_folder(solution, project)
        condition = f"CPPBUILD_WHOLE_SOLUTION OR DEFINED {variable}"
        if project.settings._data.initial_type == ProjectType.TEST:
            # BUILD_TESTING=OFF skips the TEST Projects and the GoogleTest download.
            condition = f"BUILD_TESTING AND ({condition})"
        lines += ["", f"# {project.name}: {project.settings._data.initial_type.value}, GUID {guid}",
                  f"if({condition})",
                  f"  set(CPPBUILD_REQUESTED ${{{variable}}})"]
        if kinds or folder is not None:
            lines.append("  if(CPPBUILD_WHOLE_SOLUTION)")
            if kinds:
                lines.append(f"    list(APPEND CPPBUILD_REQUESTED {' '.join(kinds)})  # links within {data.name}")
            if folder is not None:
                lines.append(f"    set(CMAKE_FOLDER {arg(folder)})")
            lines.append("  endif()")
        lines += [f"  add_subdirectory({arg(_relative(solution.root, project.root, 'A Project directory'))})", "endif()"]
    return "\n".join(lines) + "\n"


# Top level ---------------------------------------------------------------------

def top_level(plan):
    solution = plan.solution
    data = solution.settings._data
    lines = _header(".cppbuild/project.json",
                    f"Included by CMakeLists.txt when {data.name} is built as a whole: as the top-level project, "
                    "or added by a project that does not use CppBuild.")
    lines += ["if(PROJECT_IS_TOP_LEVEL)",
              "  # Defaults for the whole build; override them with -D.",
              "  get_property(_cppbuild_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)",
              "  if(NOT _cppbuild_multi_config AND NOT CMAKE_BUILD_TYPE)",
              '    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build configuration" FORCE)',
              "  endif()",
              "  if(NOT DEFINED CMAKE_CXX_STANDARD)",
              "    set(CMAKE_CXX_STANDARD 20)",
              "  endif()",
              "  if(NOT DEFINED CMAKE_RUNTIME_OUTPUT_DIRECTORY)",
              "    # Executables and DLLs side by side, so programs find their DLLs.",
              '    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")',
              "  endif()"]
    if data.solution_folders is not None:
        lines += ["  set_property(GLOBAL PROPERTY USE_FOLDERS ON)",
                  "  # ALL_BUILD, ZERO_CHECK, RUN_TESTS and the like, beside the other targets CppBuild did not write.",
                  f"  set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER {arg(data.solution_folders.external + '/CMake')})"]
    lines += ['  option(BUILD_TESTING "Build and register the TEST Projects (GoogleTest is fetched only when ON)" ON)',
              "  if(BUILD_TESTING)",
              "    enable_testing()",
              "  endif()",
              "endif()"]
    if data.solution_folders is not None:
        lines += ["", "# IDE folder of the targets CppBuild brings in, here and in linked Solutions (<folder>/GoogleTest).",
                  f"set(CPPBUILD_EXTERNAL_FOLDER {arg(data.solution_folders.external)})"]
    sources = plan.git_sources()
    if sources:
        lines += ["", "# Linked Solutions in git repositories, including the ones linked Solutions record.",
                  "# A missing place is cloned at the recorded commit; an existing one is never changed.",
                  'option(CPPBUILD_FETCH "Clone missing linked Solutions with git at their recorded commits" ON)',
                  *GIT_SOURCE_FUNCTION.splitlines(),
                  "set_property(GLOBAL PROPERTY CPPBUILD_GIT_MISSING)"]
        for status in sources:
            directory = _relative(solution.root, status.directory, "A git source place")
            lines.append(f"_cppbuild_git_source({arg(directory)} {arg(status.url)} {status.revision} {arg(status.path)})")
        lines += ["get_property(_cppbuild_missing GLOBAL PROPERTY CPPBUILD_GIT_MISSING)",
                  "if(_cppbuild_missing)",
                  '  message(FATAL_ERROR "Linked Solutions could not be fetched with git. Place each one by hand '
                  '(paths are relative to ${CMAKE_CURRENT_SOURCE_DIR}):${_cppbuild_missing}")',
                  "endif()"]
    external = plan.external_requests()
    if external:
        lines += ["", f"# Projects requested from linked Solutions, resolved with {data.name} as the top level."]
        for project, kinds in external:
            lines.append(f"set({request_variable(project.settings._data.guid)} {' '.join(kinds)})  # {alias_name(project)}")
    back = plan.member_requests()
    if back:
        lines += ["", "# Projects of this Solution requested by linked Projects."]
        for project, kinds in back:
            lines.append(f"set({request_variable(project.settings._data.guid)} {' '.join(kinds)})  # {alias_name(project)}")
    linked = plan.linked_solutions()
    if linked:
        lines += ["", "# Linked Solutions add only the Projects requested above."]
        lines.append("set(CPPBUILD_LINKED ON)")
    for other, directory, binary, folder in linked:
        lines += ["", f"# Solution {other.settings._data.name}"]
        if folder is not None:
            lines.append(f"set(CMAKE_FOLDER {arg(folder)})")
        lines += [f'set(CPPBUILD_LINKED_OUTPUT "_linked/{binary}")',
                  f'add_subdirectory({arg(directory)} "${{CMAKE_BINARY_DIR}}/${{CPPBUILD_LINKED_OUTPUT}}")',
                  f'get_property(_cppbuild_format DIRECTORY "${{CMAKE_CURRENT_SOURCE_DIR}}/{_quotable(directory)}" PROPERTY CPPBUILD_FORMAT)',
                  f'if(NOT _cppbuild_format STREQUAL "{FORMAT}")',
                  f'  message(FATAL_ERROR "{_quotable(directory)} was generated by an incompatible CppBuild '
                  f'(format ${{_cppbuild_format}}, expected {FORMAT}); regenerate its files with this CppBuild")',
                  "endif()"]
        if folder is not None:
            lines.append("unset(CMAKE_FOLDER)")
    if linked:
        lines.append("unset(CPPBUILD_LINKED_OUTPUT)")
    return "\n".join(lines) + "\n"


# Projects ----------------------------------------------------------------------

def _external_setup(project, key, value):
    """Lines that make an external dependency target available; returns (lines, target)."""
    from .dependencies import path
    root = project.root
    if isinstance(value, CMakePackage):
        directory = path(project, value.directory)
        return ([f"if(NOT TARGET {value.target})",
                 f"  find_package({value.name} CONFIG REQUIRED PATHS {_source_path(root, directory, 'A CMake package directory')} NO_DEFAULT_PATH GLOBAL)",
                 "endif()"], value.target)
    if isinstance(value, CMakeSource):
        directory = path(project, value.directory)
        return ([f"if(NOT TARGET {value.target})",
                 f"  add_subdirectory({arg(_relative(root, directory, 'A CMake source directory'))} {arg('_external/' + key)} EXCLUDE_FROM_ALL)",
                 "endif()"], value.target)
    if isinstance(value, ImportedLibrary):
        name = "external_" + key
        lines = [f"if(NOT TARGET {name})"]
        kind = value.project_type
        if kind == ProjectType.INTERFACE_LIBRARY:
            lines.append(f"  add_library({name} INTERFACE IMPORTED GLOBAL)")
        else:
            lines.append(f"  add_library({name} {'STATIC' if kind == ProjectType.STATIC_LIBRARY else 'SHARED'} IMPORTED GLOBAL)")
            def missing(configuration):
                # Unprovided configurations point at a deliberately missing path that names the
                # problem in the link error, never silently at another configuration's binary.
                return f'"${{CMAKE_CURRENT_BINARY_DIR}}/cppbuild-missing/{name}-has-no-{configuration}-file"'
            for configuration in CONFIGURATIONS:
                location = (_source_path(root, path(project, value.locations[configuration]), "An imported library")
                            if configuration in value.locations else missing(configuration))
                lines.append(f"  set_property(TARGET {name} PROPERTY IMPORTED_LOCATION_{configuration.upper()} {location})")
                if kind == ProjectType.SHARED_LIBRARY and value.import_libraries:
                    implib = (_source_path(root, path(project, value.import_libraries[configuration]), "An import library")
                              if configuration in value.import_libraries else missing(configuration))
                    lines.append(f"  set_property(TARGET {name} PROPERTY IMPORTED_IMPLIB_{configuration.upper()} {implib})")
            if kind == ProjectType.SHARED_LIBRARY and not value.import_libraries:
                # Only DLL platforms (MSVC, MinGW) link through an import library.
                lines += ["  if(CMAKE_IMPORT_LIBRARY_SUFFIX)",
                          f"    message(FATAL_ERROR {arg('Shared library ' + key + ' requires its import library on this platform')})",
                          "  endif()"]
        for directory in value.include_directories:
            lines.append(f"  set_property(TARGET {name} APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "
                         f"{_source_path(root, path(project, directory), 'An imported include directory')})")
        lines.append("endif()")
        return lines, name
    return [], None


def _links(project, providers):
    """Link items and setup lines for every dependency, in saved order."""
    setup, items = [], []
    for key, value in project.settings._data.dependencies.items():
        if isinstance(value, Dependency):
            provider = providers.get(value.project_guid)
            if provider is None:
                raise SettingsError(f"Missing dependency Project GUID: {value.project_guid}")
            items.append(link_name(provider, value.project_type))
            continue
        lines, target = _external_setup(project, key, value)
        if target is not None:
            setup += lines
            setup += [f"if(NOT TARGET {target})",
                      f"  message(FATAL_ERROR {arg('Missing external target ' + target)})", "endif()"]
            items.append(target)
    return setup, items


def _target_body(project, kind, target, items, indent):
    """Commands shared by every compiled or interface target of one type."""
    data = project.settings._data
    settings = data.types[kind]
    pad = " " * indent
    interface = kind == ProjectType.INTERFACE_LIBRARY
    # Executables have no consumers, so their requirements are PRIVATE.
    scope = "INTERFACE" if interface else "PRIVATE" if kind in {ProjectType.EXECUTABLE, ProjectType.TEST} else "PUBLIC"
    lines = []
    if settings.include_directories:
        directories = " ".join(arg(_relative(project.root, storage.contained(project.root, d), "An include directory"))
                               for d in settings.include_directories)
        lines.append(f"target_include_directories({target} {scope} {directories})")
    definitions = []
    if settings.compile_definitions and not interface:
        definitions.append("PRIVATE " + " ".join(arg(d) for d in settings.compile_definitions))
    if settings.public_definitions:
        definitions.append(scope + " " + " ".join(arg(d) for d in settings.public_definitions))
    if definitions:
        lines.append(f"target_compile_definitions({target} {' '.join(definitions)})")
    test = kind == ProjectType.TEST
    if items or test:
        lines.append(f"target_link_libraries({target} {scope} "
                     + " ".join((["GTest::gtest_main"] if test else []) + items) + ")")
    if not interface:
        headers = [arg(_relative(project.root, storage.contained(project.root, h), "A precompiled header"))
                   for h in data.project_headers]
        headers += [arg("<" + h + ">") for h in data.system_headers]
        if headers:
            lines.append(f"target_precompile_headers({target} PRIVATE {' '.join(headers)})")
        standard, output = standard_variable(project), output_variable(project)
        lines += [f"set_target_properties({target} PROPERTIES CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)",
                  f"if(DEFINED {standard})",
                  f"  set_target_properties({target} PROPERTIES CXX_STANDARD ${{{standard}}})",
                  "endif()",
                  f"if({output})",
                  f"  set_target_properties({target} PROPERTIES",
                  *(f'    {category}_OUTPUT_DIRECTORY "${{{output}}}"' for category in ("RUNTIME", "LIBRARY", "ARCHIVE", "PDB")),
                  "  )",
                  "endif()"]
    return [pad + line if line else line for line in lines]


def _compiled_sources(project, files):
    return any(p.suffix.lower() in COMPILED_SUFFIXES for p in files)


def _sources(project, files):
    listed = [arg(_relative(project.root, p, "A source file")) for p in files]
    lines = []
    if listed:
        lines += ["set(_cppbuild_sources", *("  " + item for item in listed), ")"]
        display = [arg(_relative(project.root, p, "A source file")) for p in files if p.suffix.lower() not in COMPILED_SUFFIXES]
        if display:
            lines += ["set_source_files_properties(", *("  " + item for item in display), "  PROPERTIES HEADER_FILE_ONLY TRUE)"]
    else:
        lines.append("set(_cppbuild_sources)")
    return lines


def _requested_types():
    # DISPLAY: listed for the IDE only. DISPLAY_<type>: a link type requested only by
    # Projects listed for the IDE. Neither is part of the default build.
    return ["set(_cppbuild_requested)",
            "set(_cppbuild_used_links)",
            "set(_cppbuild_display OFF)",
            "foreach(_cppbuild_item IN LISTS CPPBUILD_REQUESTED)",
            '  if(_cppbuild_item STREQUAL "DISPLAY")',
            "    set(_cppbuild_display ON)",
            '  elseif(_cppbuild_item MATCHES "^DISPLAY_(.+)$")',
            "    list(APPEND _cppbuild_requested ${CMAKE_MATCH_1})",
            "  else()",
            "    list(APPEND _cppbuild_requested ${_cppbuild_item})",
            "    list(APPEND _cppbuild_used_links ${_cppbuild_item})",
            "  endif()",
            "endforeach()",
            "list(REMOVE_DUPLICATES _cppbuild_requested)"]


def _display_only(target, output, indent):
    """Keep an IDE-listed target out of the default build, its program or DLL apart from the built ones."""
    pad = " " * indent
    lines = [f"set_target_properties({target} PROPERTIES EXCLUDE_FROM_ALL ON EXCLUDE_FROM_DEFAULT_BUILD ON)",
             f"if(CMAKE_RUNTIME_OUTPUT_DIRECTORY AND CPPBUILD_LINKED_OUTPUT AND NOT {output})",
             "  # Programs of different Solutions may share a file name.",
             f'  set_target_properties({target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${{CMAKE_RUNTIME_OUTPUT_DIRECTORY}}/${{CPPBUILD_LINKED_OUTPUT}}")',
             "endif()"]
    return [pad + line for line in lines]


def _test_setup():
    return ["if(NOT TARGET GTest::gtest_main)",
            "  include(FetchContent)",
            f'  set(CPPBUILD_GOOGLETEST_URL "{GOOGLETEST_URL}" CACHE STRING "GoogleTest 1.14.0 archive: URL or local ZIP path")',
            "  # Normal variables preset GoogleTest's options (CMP0077) without overriding the user's cache.",
            "  # Our targets use CMake's default DLL runtime, which GoogleTest must match.",
            "  set(BUILD_GMOCK OFF)",
            "  set(INSTALL_GTEST OFF)",
            "  set(gtest_force_shared_crt ON)",
            '  set(_cppbuild_googletest_url "${CPPBUILD_GOOGLETEST_URL}")',
            '  if(NOT _cppbuild_googletest_url MATCHES "^[A-Za-z][A-Za-z0-9+.-]*://")',
            "    # A local ZIP may be given with backslashes; a URL must keep its //.",
            '    file(TO_CMAKE_PATH "${_cppbuild_googletest_url}" _cppbuild_googletest_url)',
            "  endif()",
            f'  FetchContent_Declare(googletest URL "${{_cppbuild_googletest_url}}" URL_HASH SHA256={GOOGLETEST_SHA256}',
            "    DOWNLOAD_EXTRACT_TIMESTAMP TRUE TIMEOUT 60 INACTIVITY_TIMEOUT 15)",
            "  if(DEFINED CPPBUILD_EXTERNAL_FOLDER)",
            "    # Set by the top-level Solution when it lays out solution folders.",
            '    set(_cppbuild_folder "${CMAKE_FOLDER}")',
            '    set(CMAKE_FOLDER "${CPPBUILD_EXTERNAL_FOLDER}/GoogleTest")',
            "  endif()",
            "  FetchContent_MakeAvailable(googletest)",
            "  if(DEFINED CPPBUILD_EXTERNAL_FOLDER)",
            '    set(CMAKE_FOLDER "${_cppbuild_folder}")',
            "  endif()",
            "endif()"]


def test_prefix(project):
    """Discovered tests are named <Project>.<Suite>.<Test>: CTest names and labels are per tree."""
    return project.name + "."


def _test_registration(project, target):
    # CMake 4.2 requests a JSON path in UTF-8, but GoogleTest's narrow fopen on
    # Windows cannot open that path under a legacy ANSI code page. Disable only
    # discovery's JSON output; CMake also accepts the test list on stdout.
    return ["if(CPPBUILD_WHOLE_SOLUTION)",
            "  include(GoogleTest)",
            "  set(_cppbuild_discovery_args)",
            "  if(CMAKE_VERSION VERSION_GREATER_EQUAL 4.2)",
            '    set(_cppbuild_discovery_args DISCOVERY_EXTRA_ARGS "--gtest_output=")',
            "  endif()",
            f'  gtest_discover_tests({target} DISCOVERY_MODE PRE_TEST WORKING_DIRECTORY "${{CMAKE_CURRENT_SOURCE_DIR}}"',
            "    # Without a prefix, a test name shared by two TEST Projects takes both labels.",
            f"    TEST_PREFIX {arg(test_prefix(project))} PROPERTIES LABELS {target} ${{_cppbuild_discovery_args}})",
            "endif()"]


def project_entry(project, files, providers):
    data = project.settings._data
    initial = data.initial_type
    solution_name = project.solution.settings._data.name
    lines = _header(".cppbuild/project.json",
                    f"Project {project.name} of Solution {solution_name} ({initial.value}), GUID {data.guid}. "
                    "Added by the Solution's CMakeLists.txt.")
    setup, items = _links(project, providers)
    lines += _sources(project, files)
    if setup:
        lines += [""] + setup
    if initial in {ProjectType.EXECUTABLE, ProjectType.TEST}:
        target = base_name(project)
        if initial == ProjectType.TEST:
            lines += [""] + _test_setup()
        lines += ["", f"add_executable({target} ${{_cppbuild_sources}})",
                  f"set_target_properties({target} PROPERTIES OUTPUT_NAME {arg(project.name)})"]
        lines += _target_body(project, initial, target, items, 0)
        lines += ["if(DISPLAY IN_LIST CPPBUILD_REQUESTED AND NOT CPPBUILD_WHOLE_SOLUTION)",
                  "  # Listed for the IDE only: shown, but not part of the default build.",
                  *_display_only(target, output_variable(project), 2),
                  "endif()"]
        if initial == ProjectType.TEST:
            lines += [""] + _test_registration(project, target)
    else:
        lines += [""] + _library(project, files, items)
    if files:
        lines += ["", 'source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" PREFIX "" FILES ${_cppbuild_sources})']
    return "\n".join(lines) + "\n"


def _library(project, files, items):
    data = project.settings._data
    initial = KIND[data.initial_type]
    variable = type_variable(project)
    lines = _requested_types()
    lines += ["",
             f'set({variable} "" CACHE STRING "{project.name} library type: empty = {initial} (SHARED with BUILD_SHARED_LIBS) and each link keeps its saved type; '
             f'STATIC or SHARED also switch every static/shared link; INTERFACE = header-only use")',
             f'set_property(CACHE {variable} PROPERTY STRINGS "" STATIC SHARED INTERFACE)',
             f'if(NOT "${{{variable}}}" MATCHES "^(|STATIC|SHARED|INTERFACE)$")',
             f'  message(FATAL_ERROR "{variable} must be empty, STATIC, SHARED or INTERFACE")',
             "endif()",
             "",
             "# Types to create: the selected type at the top level, and every type requested by links.",
             f'set(_cppbuild_choice "${{{variable}}}")',
             *([] if initial == "INTERFACE" else
               ["if(NOT _cppbuild_choice AND BUILD_SHARED_LIBS)",
                "  # CMake's standard switch, when this library has no choice of its own.",
                "  set(_cppbuild_choice SHARED)",
                "endif()"]),
             f"set(_cppbuild_selected {initial})",
             "if(_cppbuild_choice)",
             "  set(_cppbuild_selected ${_cppbuild_choice})",
             "endif()",
             "set(_cppbuild_types)",
             "set(_cppbuild_used_types)",
             "if(CPPBUILD_WHOLE_SOLUTION)",
             "  list(APPEND _cppbuild_used_types ${_cppbuild_selected})",
             "endif()",
             "if(CPPBUILD_WHOLE_SOLUTION OR _cppbuild_display)",
             "  list(APPEND _cppbuild_types ${_cppbuild_selected})",
             "endif()",
             "foreach(_cppbuild_type IN LISTS _cppbuild_requested)",
             "  set(_cppbuild_link_${_cppbuild_type} ${_cppbuild_type})",
             '  if(_cppbuild_type MATCHES "^(STATIC|SHARED)$" AND "${_cppbuild_choice}" MATCHES "^(STATIC|SHARED)$")',
             "    set(_cppbuild_link_${_cppbuild_type} ${_cppbuild_choice})",
             "  endif()",
             "  list(APPEND _cppbuild_types ${_cppbuild_link_${_cppbuild_type}})",
             "  if(_cppbuild_type IN_LIST _cppbuild_used_links)",
             "    list(APPEND _cppbuild_used_types ${_cppbuild_link_${_cppbuild_type}})",
             "  endif()",
             "endforeach()",
             "list(REMOVE_DUPLICATES _cppbuild_types)"]
    for kind in LIBRARY_ORDER:
        lines.append(f"set(_cppbuild_target_{KIND[kind]} {target_name(project, kind)})")
    # A static library and a DLL's import library would share a file name.
    lines += ['set(_cppbuild_plain_output STATIC)',
              'if(_cppbuild_selected STREQUAL "SHARED")',
              "  set(_cppbuild_plain_output SHARED)",
              "endif()"]
    for kind in LIBRARY_ORDER:
        name = KIND[kind]
        target = target_name(project, kind)
        lines += ["", f"if({name} IN_LIST _cppbuild_types)"]
        if kind == ProjectType.INTERFACE_LIBRARY:
            lines.append(f"  add_library({target} INTERFACE)")
            if files:
                lines.append(f"  target_sources({target} PRIVATE ${{_cppbuild_sources}})")
        else:
            other = "SHARED" if kind == ProjectType.STATIC_LIBRARY else "STATIC"
            lines += [f"  add_library({target} {name} ${{_cppbuild_sources}})",
                      f"  set(_cppbuild_output {arg(project.name)})",
                      f'  if({other} IN_LIST _cppbuild_types AND NOT _cppbuild_plain_output STREQUAL "{name}")',
                      f"    set(_cppbuild_output {arg(project.name + '-' + SUFFIX[kind])})",
                      "  endif()",
                      f"  set_target_properties({target} PROPERTIES OUTPUT_NAME ${{_cppbuild_output}})"]
            if kind == ProjectType.SHARED_LIBRARY and data.windows_export_all_symbols:
                lines.append(f"  set_target_properties({target} PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)")
        lines += _target_body(project, kind, target, items, 2)
        lines.append("endif()")
    alias = alias_name(project)
    lines += ["",
              "# Consumers link <Solution>::<Project>_<saved type>; the selected type decides the target.",
              "foreach(_cppbuild_type IN LISTS _cppbuild_requested)",
              "  string(TOLOWER ${_cppbuild_type} _cppbuild_suffix)",
              f"  add_library({alias}_${{_cppbuild_suffix}} ALIAS ${{_cppbuild_target_${{_cppbuild_link_${{_cppbuild_type}}}}}})",
              "endforeach()",
              "if(TARGET ${_cppbuild_target_${_cppbuild_selected}})",
              f"  add_library({alias} ALIAS ${{_cppbuild_target_${{_cppbuild_selected}}}})",
              "endif()",
              "# Types only listed for the IDE, or linked only by such Projects, are not built by default.",
              "foreach(_cppbuild_type IN LISTS _cppbuild_types)",
              "  if(NOT _cppbuild_type IN_LIST _cppbuild_used_types)",
              *_display_only("${_cppbuild_target_${_cppbuild_type}}", output_variable(project), 4),
              "  endif()",
              "endforeach()"]
    return lines
