from pathlib import Path
import os
import sys
import tempfile
import unittest
from types import SimpleNamespace
from unittest.mock import patch

from cppbuild import ProjectBuildSettings, ProjectType as T, SettingsError, Solution
from cppbuild.cmake_files import arg as _quote
from cppbuild.engine import ProcessReport, _scan, decode_output, path_hint, process, tree


class EngineUnitTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.solution = Solution.create(Path(temporary.name) / "Demo", "Demo")
        self.app = self.solution.add_project("App", "App", T.EXECUTABLE)

    def test_deferred_empty_content_and_protected_paths(self):
        result = self.app.add_file("src/empty.hpp", content="", auto_update=False)
        self.assertTrue(result.success)
        self.assertTrue(result.pending_update)
        self.assertEqual(result.changed_paths[0].read_bytes(), b"")
        with self.assertRaises(FileExistsError):
            self.app.add_file("src/empty.hpp", content="overwrite", auto_update=False)
        for path in ("../outside.cpp", ".cppbuild/project.json", "build/output", "CMakeLists.txt"):
            with self.subTest(path=path), self.assertRaises(SettingsError):
                self.app.add_file(path, content="", auto_update=False)
        with self.assertRaises(FileNotFoundError):
            self.app.remove_file("src", auto_update=False)

    def test_update_exception_retains_completed_file_change(self):
        with patch("cppbuild.engine.update", side_effect=FileNotFoundError("cmake")):
            report = self.app.add_file("src/main.cpp", content="int main() {}")
        self.assertFalse(report.success)
        self.assertTrue(report.pending_update)
        self.assertTrue(report.changed_paths[0].exists())
        self.assertIn("FileNotFoundError", report.update_error)

    def test_failed_configure_does_not_build(self):
        self.app.add_file("src/main.cpp", content="int main() {}", auto_update=False)
        with patch("cppbuild.engine.process", return_value=ProcessReport(("cmake",), 1, "failed")) as call:
            result = self.app.build()
        self.assertFalse(result.success)
        self.assertEqual(call.call_count, 1)
        self.assertEqual(result.artifacts, ())

    def test_no_sources_fails_before_process(self):
        with patch("cppbuild.engine.process") as call:
            with self.assertRaises(SettingsError):
                self.app.update()
        call.assert_not_called()

    def test_scan_excludes_metadata_and_build(self):
        data = self.app.settings.get()
        data.source_directories = [".", "src"]
        self.app.settings.save(data)
        expected = self.app.add_file("src/main.cpp", content="int main() {}", auto_update=False).changed_paths[0]
        (self.app.root / "CMakeLists.txt").write_text("# Generated by CppBuild from x\n")
        for relative in ("build/ignore.cpp", ".git/ignore.cpp", "src/.cache/ignore.cpp"):
            path = self.app.root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("invalid code")
        self.assertEqual(_scan(self.app), (expected,))

    def test_cmake_literals_are_not_executed(self):
        self.assertIn("${VAR}", _quote("${VAR}"))
        self.assertTrue(_quote('"]=]').startswith("[==["))
        self.assertEqual(_quote("src/a b.cpp"), '"src/a b.cpp"')
        for value in ("a;b", "$<CONFIG>", "bad\nline"):
            with self.assertRaises(SettingsError):
                _quote(value)

    def test_explicit_build_source_root_is_rejected(self):
        data = self.app.settings.get()
        data.source_directories = ["build"]
        self.app.settings.save(data)
        with patch("cppbuild.engine.process") as call:
            with self.assertRaises(SettingsError):
                self.app.update()
        call.assert_not_called()

    def test_invalid_management_stops_process(self):
        self.app._last_update = object()
        self.app.settings.path.write_text("broken")
        with patch("cppbuild.engine.process") as call:
            with self.assertRaises(SettingsError):
                self.app.build()
        call.assert_not_called()
        self.assertIsNone(self.app._last_update)

    def test_unowned_build_directory_is_rejected(self):
        self.app.add_file("src/main.cpp", content="int main() {}", auto_update=False)
        path = tree(self.solution, self.app._resolved_build_settings())[0]
        path.mkdir(parents=True)
        (path / "other.txt").write_text("keep")
        with self.assertRaises(SettingsError):
            self.app.update()
        self.assertEqual((path / "other.txt").read_text(), "keep")

    def test_user_cmakelists_is_never_replaced(self):
        self.app.add_file("src/main.cpp", content="int main() {}", auto_update=False)
        own = self.app.root / "CMakeLists.txt"
        own.write_text("project(Mine)\n")
        with patch("cppbuild.engine.process") as call:
            with self.assertRaises(SettingsError):
                self.app.update()
        call.assert_not_called()
        self.assertEqual(own.read_text(), "project(Mine)\n")


class PathHintTests(unittest.TestCase):
    def test_hint_only_for_failures_in_long_windows_trees(self):
        failed, passed = ProcessReport(("cmake",), 1, "MSB4018"), ProcessReport(("cmake",), 0, "ok")
        vs, ninja = SimpleNamespace(visual_studio=True), SimpleNamespace(visual_studio=False)
        long_tree, short_tree = Path("C:/" + "d" * 140), Path("C:/b")
        with patch("cppbuild.engine.os.name", "nt"):
            hinted = path_hint(failed, long_tree, vs)
            self.assertEqual(hinted.returncode, 1)
            self.assertTrue(hinted.output.startswith("MSB4018\n"))
            self.assertIn("intermediate_directory", hinted.output)
            self.assertIs(path_hint(passed, long_tree, vs), passed)
            self.assertIs(path_hint(failed, short_tree, vs), failed)
            self.assertIs(path_hint(failed, long_tree, ninja), failed)
            self.assertIsNot(path_hint(failed, Path("C:/" + "d" * 160), ninja), failed)
        with patch("cppbuild.engine.os.name", "posix"):
            self.assertIs(path_hint(failed, long_tree, vs), failed)


class OutputDecodingTests(unittest.TestCase):
    def test_windows_lines_fall_back_to_the_ansi_code_page_each(self):
        data = "警告 utf-8\r\n".encode("utf-8") + "エラー cp932\r\n".encode("cp932") + b"end\r"
        with patch("cppbuild.engine.os.name", "nt"), patch("cppbuild.engine.locale.getencoding", return_value="cp932"):
            self.assertEqual(decode_output(data), "警告 utf-8\nエラー cp932\nend\n")

    def test_undecodable_bytes_are_replaced(self):
        with patch("cppbuild.engine.os.name", "nt"), patch("cppbuild.engine.locale.getencoding", return_value="ascii"):
            self.assertEqual(decode_output(b"\xff ok\n"), "� ok\n")
        with patch("cppbuild.engine.os.name", "posix"):
            self.assertEqual(decode_output("ok 日本\r\n".encode("utf-8") + b"\xff\n"), "ok 日本\n�\n")

    def test_process_reads_bytes_regardless_of_python_utf8_mode(self):
        code = r"import sys; sys.stdout.buffer.write('日本語'.encode('utf-8') + b'\r\n' + '語'.encode('cp932'))"
        with patch("cppbuild.engine.locale.getencoding", return_value="cp932"):
            report = process([sys.executable, "-c", code], Path.cwd())
        self.assertEqual(report.output, "日本語\n" + ("語" if os.name == "nt" else "��"))
